### ISSUE TITLE
Another sync problem

### ISSUE THREAD

**Issue by wleagle** [Martin7182/GSOSD#7]
I have trouble with my open source RX5808 diversity and the GSOSD. I am using a 3-way video switch to feed different video sources to the minimOSD. The problem is that every time the minimOSD receiving video source from the VRX diversity, the screen becomes black. I must power off the VTX, and power on again, then the video will appear. It seems that the OSD tend to use the sync from the last source, and when my VRX  has received a video signal, it triggers the sync detection of the osd.  It just can't auto detect the sync signal when it switch to the VRX. If this is the case, then how can I trigger a detection of the sync signal?

**Comment by wleagle** [comment]
Problem solved. I have replaced the AT7456 chip on my minimOSD with a MAX7456. Now everything's okay!

**Comment by Martin7182** [comment]
Thanks for reporting back @wleagle! I wrote the code for MAX7456 specifically, no wonder it doesn't work for AT7456.
